<a href="https://colab.research.google.com/github/ziyaashraf0907/python-mini-project/blob/main/Introduction_to_numpy_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6]])

In [3]:
type(arr)

numpy.ndarray

In [4]:
#Dot product - m×p||n×p
arr1=np.random.randint(1,2,(1,2))

In [5]:
arr.shape
arr1.shape

(1, 2)

In [6]:
result=np.dot(arr1,arr)

In [7]:
print(result)

[[5 7 9]]


In [8]:
r1=np.random.randint(10,30,(3,3))

In [9]:
print(r1)

[[17 22 10]
 [20 19 10]
 [20 10 22]]


In [10]:
r2=np.eye(3)

In [11]:
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#r1.I
result=np.dot(r2,r1)
print(result)

[[17. 22. 10.]
 [20. 19. 10.]
 [20. 10. 22.]]


In [17]:
#Mathematical Operations
#+,*,-,/
t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))

In [18]:
print(t1)
print(t2)

[[4 5 3]
 [3 5 5]
 [5 4 5]]
[[5 5 3]
 [5 3 3]
 [3 3 3]]


In [19]:
t3=t1+t2
print(t3)

[[ 9 10  6]
 [ 8  8  8]
 [ 8  7  8]]


In [20]:
#Matrix Multiplication
result=np.dot(arr1,arr)

In [25]:
#Statistical Operations
mean=t3.mean()
max=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [23]:
print(max)

10


In [26]:
print(median)

8.0


In [27]:
print(std)

1.0540925533894598


In [28]:
print(var)

1.1111111111111112


In [29]:
std*std

1.1111111111111112

In [31]:


#Trignometry Functions
#Sin(x)
#cos(x)
#tan-sin(x)/cos(x)
#Cosec-1/sin(x)
#sec-1/cos(x)
#cot-1/tan(x)
angles=np.array([10,15,30,45,60,75,90])

#sin(array)

result=np.sin(np.radians(angles))
result1=np.cos(np.radians(angles))
result2=np.tan(np.radians(angles))

In [34]:
print(result)
print(result1)
print(result2)

[0.17364818 0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[9.84807753e-01 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[1.76326981e-01 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [35]:
arr=np.array([1,2,3,4,5,6])
#Reshape the array
reshapedarr=arr.reshape(2,3)
print(reshapedarr)

[[1 2 3]
 [4 5 6]]


In [37]:
reshapedarr=arr.reshape(3,2)
print(reshapedarr)

[[1 2]
 [3 4]
 [5 6]]


In [40]:
#Convert/fatten any n dim array
flattenedarr=arr.flatten()
print(flattenedarr)

[1 2 3 4 5 6]


In [44]:
#Stackking the datai
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

#Vertical Stackking
arr3=np.vstack((arr1,arr2))
print(f'The shape of arr3 is {arr3.shape}')
#Horizantal Stacking
arr4=np.hstack((arr1,arr2))
print(f'The shape of arr4 is {arr4.shape}')
print(arr4)

The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [45]:
#Filttering
arr=np.array([10,20,30,40,50,60,70,80])
farr=arr[arr>40]
print(arr)

[10 20 30 40 50 60 70 80]
